In [1]:
import numpy as np

In [2]:
x=np.random.randn(209,64,64,3)

In [3]:
x.shape

(209, 64, 64, 3)

In [6]:
x.reshape(x.shape[0],-1).shape

(209, 12288)

In [7]:
a=[1,2,3]
b=[4,5,6]

In [8]:
np.dot(a,b)

32

In [12]:
a=np.array(a)

In [13]:
b=np.array(b)

In [14]:
a.shape

(3,)

In [15]:
np.dot(a.T,b.T)

32

In [20]:
a.reshape(1,3) * (b.reshape(1,3))

array([[ 4, 10, 18]])

In [19]:
a

array([1, 2, 3])

In [4]:
A=np.random.randn(4,3)
B=np.sum(A,axis=1,keepdims=True)
B.shape

(4, 1)

In [5]:
range(1,4)

range(1, 4)

In [7]:
list(range(1,4))

[1, 2, 3]

In [8]:
5 //2

2

In [9]:
6 //2

3

In [10]:
12 //7

1

In [11]:
27//12

2

In [12]:
27//7

3

In [13]:
27//5

5

In [16]:
x = np.arange(5)
np.divide(x, 4)
x/4
#array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
for l in range(1,2):
    print(l)

1
