In [6]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print('Vectorized version:', str(1000*(toc-tic)),'ms')


c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print(c)
print('For loop:', str(1000*(toc-tic)),'ms')

250216.09040860418
Vectorized version: 0.9999275207519531 ms
250216.09040860255
For loop: 770.0440883636475 ms


In [9]:
# broadcasting
A=np.array([[56.0,0.0,4.4,68.0],
           [1.2,104.0,52.0,8.0],
           [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [14]:
cal=np.sum(A,axis=0) # horizontal axis=1; vertical axis=0
print(cal)

[ 59.  239.  155.4  76.9]


In [18]:
percentage=100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [20]:
# a note on python and numpy
a=np.random.randn(5)  # rank 1 array. do not use it. 
print(a)

[ 1.15268308 -0.73363056 -0.06098388  0.09548207 -0.80718004]


In [21]:
print(a.shape)

(5,)


In [22]:
print(a.T)

[ 1.15268308 -0.73363056 -0.06098388  0.09548207 -0.80718004]


In [23]:
print(np.dot(a,a.T))

2.5312675455172826


In [24]:
a=np.random.randn(5,1)  # add 1 in a, in order to make sure it is a 1D vector
print(a)

[[-0.52136519]
 [-0.73834671]
 [-1.87527375]
 [-0.90758992]
 [ 1.91777789]]


In [25]:
print(a.T)

[[-0.52136519 -0.73834671 -1.87527375 -0.90758992  1.91777789]]


In [26]:
print(np.dot(a,a.T))

[[ 0.27182166  0.38494827  0.97770245  0.47318579 -0.99986263]
 [ 0.38494827  0.54515586  1.3846022   0.67011603 -1.41598499]
 [ 0.97770245  1.3846022   3.51665165  1.70197956 -3.59635855]
 [ 0.47318579  0.67011603  1.70197956  0.82371946 -1.74055588]
 [-0.99986263 -1.41598499 -3.59635855 -1.74055588  3.67787204]]
